# Generated by Django 4.1.7 on 2023-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('match_win', models.IntegerField(default=0)),
                ('match_tie', models.IntegerField(default=0)),
                ('match_lost', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
